# .github/workflows/ci.yml

name: CI-CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    # Service containers to run with this job
    services:
      # Label used to access the service container
      postgres:
        image: postgres:13-alpine
        # Provide environment variables for the service
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Health check to wait until postgres is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
        env:
          # This URL connects to the postgres service container
          DATABASE_URL: "postgresql://testuser:testpassword@localhost:5432/testdb"

      - name: Login to Docker Hub
        # This step only runs for pushes to the main branch after tests succeed
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        # This step also only runs for pushes to the main branch after tests succeed
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Replace 'your-repo-name' with your actual Docker Hub repository name
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculator_model:latest